### ISSUE TITLE
Smart Dashboard?

### ISSUE THREAD

**Issue by cabobalot** [pjreiniger/SnobotSim#15]
Is there support for displaying the smart dashboard?
To me this is an important feature given the lack of a graphical robot.

**Comment by pjreiniger** [comment]
If you open the SD from the driver station or by clicking on the jar, it expects to talk to the real robot (either through the USB cable, or DNS lookup, or known IP address).  If you want to use the SD locally, you need to start it and specify the IP to use (localhost).

If you are using the quickstart version, it should come with an open_smart_dashboard.bat script that makes it simple to do.  Otherwise you can download the one from the [repo](https://github.com/pjreiniger/SnobotSim/blob/master/snobot_sim_gui/open_smart_dashboard.bat) and use that for convenience.

**Comment by cabobalot** [comment]
Oh, that was a little obvious. Thanks though!
